-- =====================================================================
-- Tutee Connect: enquiry leads table for the landing-page form
-- =====================================================================
-- Run once in Supabase -> SQL Editor. Safe to re-run: every statement is
-- "if not exists" / "or replace", so it will not touch rows you already have.
--
-- How a lead gets here:
--   browser form  ->  POST /api/enquiry  (Netlify function netlify/functions/enquiry.mjs)
--                 ->  Supabase REST insert with the SERVICE ROLE key (server-side only)
--                 ->  public.leads
--
-- The browser never talks to this table. Row Level Security is ON and there is
-- deliberately NO policy for the anon or authenticated roles, so the public
-- anon key in assets/js/supabase-config.js cannot read or write a single lead.
-- Only the service role (Netlify env var SUPABASE_SERVICE_ROLE_KEY) and you in
-- the Supabase dashboard can see them.

create table if not exists public.leads (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  country      text,          -- landing page, e.g. 'Singapore'
  name         text not null,
  email        text not null,
  phone        text not null, -- e.g. '+91 98765 43210'
  destination  text,          -- hidden form field, 'Singapore'
  source       text,          -- hidden form field, 'Tutee Connect Singapore'
  page         text,          -- host + path the form was sent from
  extras       jsonb not null default '{}'::jsonb,
                              -- every other form field, e.g.
                              -- {"study_level":"Bachelor's degree",
                              --  "call_slot":"Evening, 4–8pm",
                              --  "origin_city":"India","description":"..."}
  status       text not null default 'new'   -- for your team: new / contacted / closed
);

-- If the table already existed from an earlier setup, make sure the newer
-- columns are present too.
alter table public.leads add column if not exists extras jsonb not null default '{}'::jsonb;
alter table public.leads add column if not exists status text not null default 'new';
alter table public.leads add column if not exists page   text;

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_country_idx    on public.leads (country);

-- Lock it down: RLS on, no public policies.
alter table public.leads enable row level security;
revoke all on public.leads from anon, authenticated;

-- A readable view of the Singapore leads with the form extras as columns.
-- Views run with the owner's rights by default, so restrict it the same way.
create or replace view public.leads_singapore
with (security_invoker = true) as
select
  id,
  created_at,
  name,
  email,
  phone,
  extras ->> 'study_level'  as study_level,
  extras ->> 'call_slot'    as call_slot,
  extras ->> 'origin_city'  as from_country,
  extras ->> 'description'  as note,
  status,
  page,
  extras ->> 'shortlist'    as shortlist   -- universities the student picked, in their order (added last so the view can be replaced in place)
from public.leads
where country = 'Singapore'
order by created_at desc;

revoke all on public.leads_singapore from anon, authenticated;

-- Quick check after your first test submission:
--   select * from public.leads_singapore limit 20;
